pyxplot 0.8.3-1 : new upstream release
long time in the making, due to linking flag related build error

diff --git a/myaurpackages/pyxplot/configure.patch b/myaurpackages/pyxplot/configure.patch
--- a/myaurpackages/pyxplot/configure.patch
+++ b/myaurpackages/pyxplot/configure.patch
@@ -1,5 +1,5 @@
---- configure.old	2010-08-28 12:15:31.000000000 +0800
-+++ configure	2010-08-28 12:17:27.000000000 +0800
+--- configure.old	2010-10-09 12:25:07.000000000 +0800
++++ configure	2010-10-09 12:44:07.000000000 +0800
 @@ -197,7 +197,7 @@
   rm -f conf.*
   echo "YES"
@@ -25,11 +25,65 @@
   echo "NO"
   echo "HAVE_KPATHSEA=-D NOHAVE_KPATHSEA=1" >> Makefile
   echo "LINK_KPATHSEA=" >> Makefile
-@@ -343,7 +334,6 @@
+@@ -343,8 +334,37 @@
   else
    echo "NO" ; echo "ERROR: Neither the header files for the library 'libkpathsea-dev', nor the program kpsewhich could not be found." >&2 ; exit
   fi
--fi
++
++
++# +1 CHECK FOR PYTHON 2
++echo $ECHO_N "Checking for suitable Python   ............. $ECHO_C"
++whichout_python=`which python 2> conf.stderr`
++rm -f conf.*
++unset PY_MAJOR PY_MID PY_MIN
++eval `$whichout_python -V 2>&1 | awk '{printf("PY_MAJOR=%d\nPY_MID=%d\nPY_MIN=%d\n",substr($2,1,1),substr($2,3,1),substr($2,5,1));}'`
++if [ $PY_MAJOR -gt 2 ]
++then
++  whichout_python=`which python2 2> conf.stderr`
++  rm -f conf.*
++  unset PY_MAJOR PY_MID PY_MIN
++  eval `$whichout_python -V 2>&1 | awk '{printf("PY_MAJOR=%d\nPY_MID=%d\nPY_MIN=%d\n",substr($2,1,1),substr($2,3,1),substr($2,5,1));}'`
++  if [ $PY_MAJOR -eq 2 ]
++  then
++    echo "YES ($whichout_python)"
++    echo "PYTHON_COMMAND=${whichout_python}" >> Makefile
++    PYTHON_COMMAND="$whichout_python"
++  else
++    echo "NO"
++    echo "ERROR: Required python 2.x.x version could not be found." >&2
++    exit
++  fi
++else
++  echo "YES ($whichout_python)"
++  echo "PYTHON_COMMAND=${whichout_python}" >> Makefile
++  PYTHON_COMMAND="$whichout_python"
+ fi
  
++
  # 20. OUTPUT MAKEFILE
  
+ cat Makefile.skel >> Makefile
+--- Makefile.skel.old	2010-10-09 12:46:17.000000000 +0800
++++ Makefile.skel	2010-10-09 12:48:34.000000000 +0800
+@@ -94,7 +94,7 @@
+ all: $(LOCAL_BINDIR)/pyxplot $(LOCAL_BINDIR)/pyxplot_watch $(LOCAL_BINDIR)/pyxplot_fitshelper $(LOCAL_BINDIR)/pyxplot_timehelper $(LOCAL_BINDIR)/debug/pyxplot $(LOCAL_BINDIR)/debug/pyxplot_watch $(LOCAL_BINDIR)/install/pyxplot $(LOCAL_BINDIR)/install/pyxplot_watch $(LOCAL_BINDIR)/install/pyxplot_fitshelper $(LOCAL_BINDIR)/install/pyxplot_timehelper pyxplot.1 pyxplot_watch.1
+ 
+ src/EPSMaker/eps_colours.h: colourlist_generate.py
+-	python colourlist_generate.py
++	$(PYTHON_COMMAND) colourlist_generate.py
+ 
+ src/EPSMaker/eps_colours.c: src/EPSMaker/eps_colours.h
+ 
+@@ -177,10 +177,10 @@
+ #
+ 
+ pyxplot.1: manpage_pyxplot.py
+-	python manpage_pyxplot.py       ${DOCDIR}/pyxplot.pdf > pyxplot.1
++	$(PYTHON_COMMAND) manpage_pyxplot.py       ${DOCDIR}/pyxplot.pdf > pyxplot.1
+ 
+ pyxplot_watch.1: manpage_pyxplot_watch.py
+-	python manpage_pyxplot_watch.py ${DOCDIR}/pyxplot.pdf > pyxplot_watch.1
++	$(PYTHON_COMMAND) manpage_pyxplot_watch.py ${DOCDIR}/pyxplot.pdf > pyxplot_watch.1
+ 
+ 
+ #
